### PR TITLE
[Release 4.0][Fix] 7905 custom field not removed from cost report after delete

### PR DESCRIPTION
**Pull request by hschink**
[`* `#7905` Custom field not removed from cost report on deletion`](https://www.openproject.org/work_packages/7905)

### CODE REVIEW

**Comment by kgalli** [comment]
I think there are changes missing to adjust session data. Right now I can not verify that the changes fix the bug entirely. It is working if I log out and in again, so that my session data is cleared. Otherwise it doesn't work.

**Comment by hschink** [comment]
@kgalli I commited a spec and fixed the issue you described. Thanks for reporting! :+1:

**Comment by kgalli** [comment]
@hschink I might found a problem with the new implementation. I get the following error: 

``` ruby
NameError (uninitialized constant Report::GroupBy::Week)
```

It seems to me that this problem is related to the reporting-engine version I'm using. Could that be the case? I'm using stable (1.0.0).

**Comment by hschink** [comment]
@kgalli could you send steps to reproduce the error? I have a release 3.0 setup running.

**Pull request merged**
